Feature/adm 197
flow-build/diagrams-core pull request #26
Opened 2023-05-08 16:49 UTC by pedropereiraassis

2023-05-08 18:20 UTC, gustavo-fdte requested changes

2023-05-08 18:20 UTC, gustavo-fdte commented on db/migrations/20230503190508_create_blueprint_table.js
> +    table.jsonb("blueprint_spec").notNullable().unique();
Sei que conceitualmente está correto, mas o banco vai conseguir validar se é unique mesmo?
Eu removeria a condição de faria a validação na aplicação e não no banco.

2023-05-08 18:20 UTC, gustavo-fdte commented on db/migrations/20230503190851_create_server_table.js
> +    table.jsonb("event_broker").nullable();
troca o nome da coluna para config... Quero deixar ela aberta para colocar mais configurações além só a configuração do broker (que no limite tbm pode ser +1)

2023-05-08 18:20 UTC, gustavo-fdte commented on db/migrations/20230503190858_create_workflow_table.js
> +    table.primary(["id", "server_id"]);
não entendi porque uma chave composta aqui.
O id já é um registro único.
O que poderia ser um unique seria server_id + blueprint_id, mas ainda assim eu não colocaria essa trava nesse momento.

2023-05-08 18:41 UTC, pedropereiraassis commented on db/migrations/20230503190858_create_workflow_table.js
> +    table.primary(["id", "server_id"]);
Isso era pro caso de em dois servers diferentes acabar tendo workflows com o mesmo id.. Mas posso remover isso por agora

2023-05-09 19:31 UTC, imagure approved these changes

2023-05-09 19:31 UTC, merged

2023-05-09 19:32 UTC, gharamura commented
:tada: This PR is included in version 1.6.0-rc.1 :tada:

The release is available on:
- [npm package (@rc dist-tag)](https://www.npmjs.com/package/@flowbuild/diagrams-core/v/1.6.0-rc.1)
- [GitHub release](https://github.com/flow-build/diagrams-core/releases/tag/v1.6.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-16 15:46 UTC, gustavo-fdte commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@flowbuild/diagrams-core/v/1.6.0)
- [GitHub release](https://github.com/flow-build/diagrams-core/releases/tag/v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: